config/routes.rb
Rails.application.routes.draw do
  resources :dvds, constraints: ->(request){ !request.format.html? }
  devise_for :users

  get '*path', to: 'pages#protected', constraints: ->(request){ request.format.html? }
  root to: 'pages#unprotected'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dvd.rb
class Dvd < ApplicationRecord
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dvds_controller.rb
class DvdsController < ApplicationController
  before_action :set_dvd, only: [:show, :edit, :update, :destroy]

  # GET /dvds
  # GET /dvds.json
  def index
    @dvds = Dvd.all
  end

  # GET /dvds/1
  # GET /dvds/1.json
  def show
  end

  # GET /dvds/new
  def new
    @dvd = Dvd.new
  end

  # GET /dvds/1/edit
  def edit
  end

  # POST /dvds
  # POST /dvds.json
  def create
    @dvd = Dvd.new(dvd_params)

    respond_to do |format|
      if @dvd.save
        format.html { redirect_to @dvd, notice: 'Dvd was successfully created.' }
        format.json { render :show, status: :created, location: @dvd }
      else
        format.html { render :new }
        format.json { render json: @dvd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dvds/1
  # PATCH/PUT /dvds/1.json
  def update
    respond_to do |format|
      if @dvd.update(dvd_params)
        format.html { redirect_to @dvd, notice: 'Dvd was successfully updated.' }
        format.json { render :show, status: :ok, location: @dvd }
      else
        format.html { render :edit }
        format.json { render json: @dvd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dvds/1
  # DELETE /dvds/1.json
  def destroy
    @dvd.destroy
    respond_to do |format|
      format.html { redirect_to dvds_url, notice: 'Dvd was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dvd
      @dvd = Dvd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dvd_params
      params.require(:dvd).permit(:title, :year, :genre)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: :protected

  def unprotected
  end

  def protected
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dvds_helper.rb
module DvdsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dvds/_form.html.erb
<%= form_with(model: dvd, local: true) do |form| %>
  <% if dvd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dvd.errors.count, "error") %> prohibited this dvd from being saved:</h2>

      <ul>
      <% dvd.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dvds/edit.html.erb
<h1>Editing Dvd</h1>

<%= render 'form', dvd: @dvd %>

<%= link_to 'Show', @dvd %> |
<%= link_to 'Back', dvds_path %>

app/views/dvds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dvds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Year</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dvds.each do |dvd| %>
      <tr>
        <td><%= dvd.title %></td>
        <td><%= dvd.year %></td>
        <td><%= dvd.genre %></td>
        <td><%= link_to 'Show', dvd %></td>
        <td><%= link_to 'Edit', edit_dvd_path(dvd) %></td>
        <td><%= link_to 'Destroy', dvd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dvd', new_dvd_path %>

app/views/dvds/new.html.erb
<h1>New Dvd</h1>

<%= render 'form', dvd: @dvd %>

<%= link_to 'Back', dvds_path %>

app/views/dvds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @dvd.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @dvd.year %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @dvd.genre %>
</p>

<%= link_to 'Edit', edit_dvd_path(@dvd) %> |
<%= link_to 'Back', dvds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseSinglePageApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/protected.html.erb
<%= react_component('AuthenticatedApp') %>

app/views/pages/unprotected.html.erb
<%= react_component('UnauthenticatedApp') %>